name: Actualizar Galería

on:
  repository_dispatch:
    types: [update_gallery]

permissions:
  contents: write
  actions: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Merge JSON
        run: |
          jq -s 'reduce .[] as $item (.; . + $item)' data/recuerdos.json <(echo '${{ toJson(github.event.client_payload.data) }}') > temp.json
          mv temp.json data/recuerdos.json

      - name: Commit y Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/recuerdos.json
          git commit -m "Actualizar galería" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
