name: Actualizar Galería

on:
  repository_dispatch:
    types: [update_gallery]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Actualizar JSON
        run: |
          FILE="data/recuerdos.json"
          PAYLOAD='${{ toJson(github.event.client_payload.data) }}'

          # Crear archivo si no existe
          [ -f "$FILE" ] || echo "[]" > "$FILE"

          # Combinar arrays
          jq -s 'reduce .[] as $item (.; . + $item)' "$FILE" <(echo "$PAYLOAD") > temp.json
          mv temp.json "$FILE"

      - name: Commit y Push
        run: |
          git config user.name "Pipedream"
          git config user.email "pipedream@github.com"
          git add data/recuerdos.json
          git commit -m "Actualizar galería" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
