name: Actualizar Galería

on:
  repository_dispatch:
    types: [update_gallery]

permissions:
  contents: write
  actions: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar jq
        run: sudo apt-get install -y jq

      - name: Actualizar JSON
        run: |
          INPUT='data/recuerdos.json'
          PAYLOAD='${{ toJson(github.event.client_payload.data) }}'
          
          if [ ! -f "$INPUT" ]; then
            echo "[]" > "$INPUT"
          fi
          
          jq -s 'reduce .[] as $item (.; . + $item)' "$INPUT" <(echo "$PAYLOAD") > temp.json
          mv temp.json "$INPUT"

      - name: Commit y Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/recuerdos.json
          git commit -m "Actualizar galería" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
